SELECT * FROM "FINANZAS"."CARTERA";
SELECT * FROM "FINANZAS"."RENDIMIENTOS";
SELECT * FROM "FINANZAS"."DIVIDENDOS";

--SUMAR DE LA TABLA "FINANZAS"."RENDIMIENTOS" los dividendos totales cobrados:
SELECT CATEGORIA_NIVEL_DOS, SUM(DIVIDENDO_EUR) FROM "FINANZAS"."DIVIDENDOS"
GROUP BY CATEGORIA_NIVEL_DOS;

--SUMAR DE LA TABLA "FINANZAS"."RENDIMIENTOS" los dividendos totales cobrados para cada ISIN:
SELECT ISIN, SUM(DIVIDENDO_EUR) AS DIVIDENDO_EUR FROM "FINANZAS"."DIVIDENDOS"
GROUP BY ISIN;


--TOMAR DE LA TABLA "FINANZAS"."RENDIMIENTOS" la fecha más reciente para cada ISIN:
	SELECT TABLA_RENDIMIENTOS.ISIN, TABLA_RENDIMIENTOS.FECHA, TABLA_RENDIMIENTOS.ACTIVO, TABLA_RENDIMIENTOS.PRECIO, TABLA_RENDIMIENTOS.CIERRE 
	FROM "FINANZAS"."RENDIMIENTOS" AS TABLA_RENDIMIENTOS
INNER JOIN
	(SELECT ISIN, MAX(FECHA) AS FECHA FROM "FINANZAS"."RENDIMIENTOS"
	GROUP BY ISIN) AS TABLA_ULTIMOS_RENDIMIENTOS
ON TABLA_RENDIMIENTOS.ISIN = TABLA_ULTIMOS_RENDIMIENTOS.ISIN
AND TABLA_RENDIMIENTOS.FECHA = TABLA_ULTIMOS_RENDIMIENTOS.FECHA;


--RELLENAR EN LA TABLA "FINANZAS"."RENDIMIENTOS" las plusvalias/minusvalias para cada registro:

SELECT TABLA_RENDIMIENTOS.ISIN, TABLA_RENDIMIENTOS.FECHA, TABLA_RENDIMIENTOS.ACTIVO, TABLA_RENDIMIENTOS.PRECIO AS PRECIO, TABLA_RENDIMIENTOS.CIERRE AS CIERRE, 
CIERRE-PRECIO AS PLUSVALIA_MINUSVALIA FROM "FINANZAS"."RENDIMIENTOS" AS TABLA_RENDIMIENTOS;


-- TOMAR DE LA TABLA "FINANZAS"."RENDIMIENTOS" las plusvalias/minusvalias para cada ISIN:

SELECT TABLA_RENDIMIENTOS.ISIN, TABLA_RENDIMIENTOS.FECHA, TABLA_RENDIMIENTOS.ACTIVO, TABLA_RENDIMIENTOS.PRECIO AS PRECIO, TABLA_RENDIMIENTOS.CIERRE AS CIERRE, 
	CIERRE-PRECIO AS PLUSVALIA_MINUSVALIA 
	FROM "FINANZAS"."RENDIMIENTOS" AS TABLA_RENDIMIENTOS
INNER JOIN
	(SELECT ISIN, MAX(FECHA) AS FECHA FROM "FINANZAS"."RENDIMIENTOS"
	GROUP BY ISIN) AS TABLA_ULTIMOS_RENDIMIENTOS
ON TABLA_RENDIMIENTOS.ISIN = TABLA_ULTIMOS_RENDIMIENTOS.ISIN
AND TABLA_RENDIMIENTOS.FECHA = TABLA_ULTIMOS_RENDIMIENTOS.FECHA






--VISTAS FINALES:

--VISTA RENDIMIENTOS_CURRENT_DATE:

--CREO LA VISTA DE: TOMAR DE LA TABLA "FINANZAS"."RENDIMIENTOS" las plusvalias/minusvalias para cada ISIN.
--Esta vista también almacena LAS NUEVAS COMPRAS REALIZADAS EN UNA FECHA DISTINTA A LA ACTUAL:

CREATE VIEW "FINANZAS"."RENDIMIENTOS_CURRENT_DATE" AS
SELECT TABLA_CARTERA.ISIN, TABLA_CARTERA.activo, TABLA_CARTERA.CANTIDAD, TABLA_CARTERA.precio AS PRECIO_MEDIO, TABLA_CARTERA.FECHA AS FECHA_PRIMERA_OPERACION, 
TABLA_RENDIMIENTOS.cierre AS PRECIO_ACTUAL, TABLA_RENDIMIENTOS.fecha AS FECHA_ACTUAL, TABLA_RENDIMIENTOS.plusvalia_minusvalia
FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
INNER JOIN 

	(SELECT ISIN, FECHA, ACTIVO, PRECIO, CIERRE, 
		CIERRE-PRECIO AS PLUSVALIA_MINUSVALIA 
		FROM "FINANZAS"."RENDIMIENTOS") AS TABLA_RENDIMIENTOS
	INNER JOIN
	(SELECT ISIN, MAX(FECHA) AS FECHA FROM "FINANZAS"."RENDIMIENTOS"
	GROUP BY ISIN) AS TABLA_ULTIMOS_RENDIMIENTOS
	ON TABLA_RENDIMIENTOS.ISIN = TABLA_ULTIMOS_RENDIMIENTOS.ISIN
	AND TABLA_RENDIMIENTOS.FECHA = TABLA_ULTIMOS_RENDIMIENTOS.FECHA

ON TABLA_CARTERA.ISIN = TABLA_ULTIMOS_RENDIMIENTOS.ISIN;

SELECT * FROM "FINANZAS"."RENDIMIENTOS_CURRENT_DATE";



--AGRUPAR VARIAS OPERACIONES DE "COMPRA" Y CALCULAR SU PRECIO_MEDIO:
--BIEN
SELECT TABLA_CARTERA.ISIN,  TABLA_CARTERA.TIPO_DE_OPERACION, SUM(precio)/COUNT(TABLA_CONTEO.num_isin_compra) AS PRECIO_MEDIO
FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
INNER JOIN
		(SELECT ISIN, TIPO_DE_OPERACION, COUNT(ISIN) AS num_isin_compra
		 FROM "FINANZAS"."CARTERA"
		 GROUP BY ISIN, TIPO_DE_OPERACION) AS TABLA_CONTEO

ON TABLA_CARTERA.ISIN = TABLA_CONTEO.ISIN
WHERE TABLA_CARTERA.TIPO_DE_OPERACION = 'COMPRA' 	--SOLO TOMAMOS LAS COMPRAS
GROUP BY TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION


--Dada la tabla anterior. AGRUPAR VARIAS OPERACIONES DE "COMPRA" Y CALCULAR SU PRECIO_MEDIO y cruzar con rendimienots_current_date
--para obtener las plusvalias_minusvalias CON LOS PRECIO_MEDIO:


--CALCULAR LA MEDIA PONDERADA:

WITH CTE_SUMA_CANTIDAD AS (
	SELECT TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION, SUM(TABLA_CARTERA.CANTIDAD) AS CANTIDAD
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	WHERE TABLA_CARTERA.TIPO_DE_OPERACION = 'COMPRA'
	GROUP BY TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION
),

CTE_PRODUCTO_PRECIO_CANTIDAD AS (
	SELECT TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION, SUM(TABLA_CARTERA.PRECIO_EUR) AS PRECIO_EUR
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	WHERE TABLA_CARTERA.TIPO_DE_OPERACION = 'COMPRA'
	GROUP BY TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION
)

	SELECT CTE_SUMA_CANTIDAD.ISIN, CTE_SUMA_CANTIDAD.TIPO_DE_OPERACION,  CTE_SUMA_CANTIDAD.CANTIDAD AS CANTIDAD, 
	PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR --¡EL PRECIO MEDIO EN EUROS!
	FROM CTE_SUMA_CANTIDAD
INNER JOIN
	(SELECT ISIN, PRECIO_EUR, TIPO_DE_OPERACION
	FROM CTE_PRODUCTO_PRECIO_CANTIDAD) AS CTE_PRODUCTO
ON CTE_SUMA_CANTIDAD.ISIN = CTE_PRODUCTO.ISIN



-- BIEN: TOMAR EL PRECIO_MEDIO_EUR para el calculo de plusvalia_minusvalia:
--INCORPORACIÓN DE FECHA_ACTUAL EN LA MISMA TABLA <- BIEN:

WITH CTE_SUMA_CANTIDAD AS (
	SELECT TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION, SUM(TABLA_CARTERA.CANTIDAD) AS CANTIDAD
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	WHERE TABLA_CARTERA.TIPO_DE_OPERACION = 'COMPRA'
	GROUP BY TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION
),

CTE_PRODUCTO_PRECIO_CANTIDAD AS (
	SELECT TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION, SUM(TABLA_CARTERA.PRECIO_EUR) AS PRECIO_EUR
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	WHERE TABLA_CARTERA.TIPO_DE_OPERACION = 'COMPRA'
	GROUP BY TABLA_CARTERA.ISIN, TABLA_CARTERA.TIPO_DE_OPERACION
),

/*
CTE_TABLA_PRECIOS_MEDIOS AS (
		SELECT CTE_SUMA_CANTIDAD.ISIN, CTE_SUMA_CANTIDAD.TIPO_DE_OPERACION, CTE_SUMA_CANTIDAD.CANTIDAD AS CANTIDAD, 
		PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR
		FROM CTE_SUMA_CANTIDAD
	INNER JOIN
		(SELECT ISIN, PRECIO_EUR, TIPO_DE_OPERACION
		FROM CTE_PRODUCTO_PRECIO_CANTIDAD) AS CTE_PRODUCTO
	ON CTE_SUMA_CANTIDAD.ISIN = CTE_PRODUCTO.ISIN
),
*/

CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL AS (
		SELECT CTE_SUMA_CANTIDAD.ISIN, CTE_SUMA_CANTIDAD.TIPO_DE_OPERACION, 
	CTE_SUMA_CANTIDAD.CANTIDAD AS CANTIDAD,	
	PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR, TABLA_FECHA.FECHA_ACTUAL --, TABLA_FECHA.ACTIVO, TABLA_FECHA.TIPO_DE_ACTIVO,TABLA_FECHA.CIERRE
		FROM CTE_SUMA_CANTIDAD
	INNER JOIN
		(SELECT ISIN, PRECIO_EUR, TIPO_DE_OPERACION
		FROM CTE_PRODUCTO_PRECIO_CANTIDAD) AS CTE_PRODUCTO
	ON CTE_SUMA_CANTIDAD.ISIN = CTE_PRODUCTO.ISIN
	INNER JOIN
	(SELECT ISIN, MAX(FECHA) AS FECHA_ACTUAL
		FROM "FINANZAS"."RENDIMIENTOS"
		GROUP BY ISIN) AS TABLA_FECHA
	ON TABLA_FECHA.ISIN = CTE_PRODUCTO.ISIN
	--AND TABLA_RENDIMIENTOS.FECHA = TABLA_ULTIMOS_RENDIMIENTOS.FECHA --SOLUCIÓN: NECESITO ESCRIBIR ESTO PARA LOS CRUCES. EL PROBLEMA ES QUE 
/*																	  --FECHA NO SE ENCUENTRA EN CTE_PRODUCTO NI CTE_PRODUCTO_PRECIO_CANTIDAD
	INNER JOIN
	(SELECT ISIN, FECHA, TIPO_DE_ACTIVO, PRECIO_MEDIO_EUR, CIERRE, 
		 CIERRE-PRECIO_MEDIO_EUR AS PLUSVALIA_MINUSVALIA 
		 FROM "FINANZAS"."RENDIMIENTOS") AS TABLA_RENDIMIENTOS
	ON TABLA_RENDIMIENTOS.ISIN = TABLA_FECHA.ISIN 
*/
)

SELECT * FROM CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL


--BIEN: Utilizamos el PRECIO MEDIO para calcular la plusvalia_minusvalia
--para LA FECHA MÁS RECIENTE para cada ISIN de TABLA_RENDIMIENTOS:
WITH CTE_SUMA_CANTIDAD_PRECIO_EUR AS (

	SELECT ISIN, TIPO_DE_OPERACION, CANTIDAD, PRECIO_EUR
FROM 
	(SELECT ISIN, TIPO_DE_OPERACION, SUM(CANTIDAD) AS CANTIDAD,
	SUM(PRECIO_EUR) AS PRECIO_EUR
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	WHERE TIPO_DE_OPERACION = 'COMPRA'
	GROUP BY ISIN, TIPO_DE_OPERACION)
),

CTE_TABLA_PRECIOS_MEDIOS AS (
		SELECT CTE_SUMA_CANTIDAD_PRECIO_EUR.ISIN, CTE_SUMA_CANTIDAD_PRECIO_EUR.TIPO_DE_OPERACION, CTE_SUMA_CANTIDAD_PRECIO_EUR.CANTIDAD AS CANTIDAD, 
		CTE_SUMA_CANTIDAD_PRECIO_EUR.PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR
		FROM CTE_SUMA_CANTIDAD_PRECIO_EUR
),

CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL AS (
		SELECT CTE_SUMA_CANTIDAD_PRECIO_EUR.ISIN, CTE_SUMA_CANTIDAD_PRECIO_EUR.TIPO_DE_OPERACION, 
			CTE_SUMA_CANTIDAD_PRECIO_EUR.CANTIDAD AS CANTIDAD,	
			PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR, TABLA_FECHA.FECHA_ACTUAL --, TABLA_FECHA.ACTIVO, TABLA_FECHA.TIPO_DE_ACTIVO,TABLA_FECHA.CIERRE
		FROM CTE_SUMA_CANTIDAD_PRECIO_EUR
	INNER JOIN
		(SELECT ISIN, PRECIO_EUR, TIPO_DE_OPERACION
		FROM CTE_TABLA_PRECIOS_MEDIOS) AS CTE_PRODUCTO
	ON CTE_TABLA_PRECIOS_MEDIOS.ISIN = CTE_PRODUCTO.ISIN
	INNER JOIN
	(SELECT ISIN, MAX(FECHA) AS FECHA_ACTUAL
		FROM "FINANZAS"."RENDIMIENTOS"
		GROUP BY ISIN) AS TABLA_FECHA
	ON TABLA_FECHA.ISIN = CTE_PRODUCTO.ISIN
	--AND TABLA_RENDIMIENTOS.FECHA = TABLA_ULTIMOS_RENDIMIENTOS.FECHA --SOLUCIÓN: NECESITO ESCRIBIR ESTO. EL PROBLEMA ES QUE 
																	  --FECHA NO SE ENCUENTRA EN CTE_PRODUCTO NI CTE_PRODUCTO_PRECIO_CANTIDAD
)

--SELECT * FROM CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL

SELECT CTE_SUMA_CANTIDAD.ISIN, CTE_SUMA_CANTIDAD.TIPO_DE_OPERACION, 
			CTE_SUMA_CANTIDAD.CANTIDAD AS CANTIDAD,	
			PRECIO_EUR/CANTIDAD AS PRECIO_EUR, TABLA_FECHA.FECHA_ACTUAL --, TABLA_FECHA.ACTIVO, TABLA_FECHA.TIPO_DE_ACTIVO,TABLA_FECHA.CIERRE
FROM CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL
INNER JOIN
	(SELECT ISIN, PRECIO_MEDIO_EUR, CIERRE, --PENDIENTE: Poner el CIERRE EN las CTEs de arriba
		 CIERRE-PRECIO_EUR AS PLUSVALIA_MINUSVALIA 
		 FROM CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL) AS TABLA_RENDIMIENTOS
	ON CTE_TABLA_PRECIOS_MEDIOS_FECHA_ACTUAL.ISIN = TABLA_RENDIMIENTOS.ISIN 






--SOLUCIÓN DEFINITIVA: Utilizamos el PRECIO MEDIO para calcular la plusvalia_minusvalia
--para LA FECHA MÁS RECIENTE para cada ISIN de TABLA_RENDIMIENTOS:
--HEMOS INCLUIDO LA COLUMNA 'CIERRE' PARA PODER CALCULAR
--LAS PLUSVALIAS_MINUSVALIAS: CIERRE-PRECIO_MEDIO_EUR


CREATE VIEW "FINANZAS"."RENDIMIENTOS_CURRENT_DATE" AS

WITH CTE_SUMA_CANTIDAD_PRECIO_EUR AS (

	SELECT ISIN, TIPO_DE_OPERACION, CANTIDAD, PRECIO_EUR
FROM 
	(SELECT ISIN, TIPO_DE_OPERACION, SUM(CANTIDAD) AS CANTIDAD,
	SUM(PRECIO_EUR) AS PRECIO_EUR
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	WHERE TIPO_DE_OPERACION = 'COMPRA'
	GROUP BY ISIN, TIPO_DE_OPERACION)
	
),

CTE_TABLA_PRECIOS_MEDIOS AS (
		SELECT CTE_SUMA_CANTIDAD_PRECIO_EUR.ISIN, CTE_SUMA_CANTIDAD_PRECIO_EUR.TIPO_DE_OPERACION, CTE_SUMA_CANTIDAD_PRECIO_EUR.CANTIDAD AS CANTIDAD, 
		CTE_SUMA_CANTIDAD_PRECIO_EUR.PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR
		FROM CTE_SUMA_CANTIDAD_PRECIO_EUR
)

--SELECT * FROM CTE_TABLA_PRECIOS_MEDIOS

SELECT CTE_TABLA_PRECIOS_MEDIOS.ISIN, TIPO_DE_OPERACION, 
	CANTIDAD,
	CIERRE, 
	TABLA_FECHA.FECHA_ACTUAL,
	--FECHA, --Para ver las fechas diarias
	PRECIO_MEDIO_EUR,
	CIERRE-PRECIO_MEDIO_EUR AS PLUSVALIA_MINUSVALIA
FROM 
	CTE_TABLA_PRECIOS_MEDIOS 
	INNER JOIN 
	(SELECT ISIN, FECHA, CIERRE FROM "FINANZAS"."RENDIMIENTOS") AS TABLA_RENDIMIENTOS

	ON TABLA_RENDIMIENTOS.ISIN = CTE_TABLA_PRECIOS_MEDIOS.ISIN

	--Hacemos cruce con este JOIN para que tome la ÚLTIMA FECHA para cada ISIN:
	INNER JOIN
		(SELECT ISIN, MAX(FECHA) AS FECHA_ACTUAL
			FROM "FINANZAS"."RENDIMIENTOS"
			GROUP BY ISIN) AS TABLA_FECHA
	ON TABLA_RENDIMIENTOS.ISIN = TABLA_FECHA.ISIN
	AND TABLA_RENDIMIENTOS.FECHA = TABLA_FECHA.FECHA_ACTUAL
; --AS TABLA_CON_CIERRES_DIARIOS






--PENDIENTE: Mejorar la vista anterior para tratar el caso de las VENTAS (ver Excalidraw).



/* SOBRE EL OVER PARTITION BY:

CTE_SUMA_CANTIDAD_VENTAS_over_partition AS (
	SELECT ISIN, 
		   TIPO_DE_OPERACION, 
		   CANTIDAD,
		   SUM(CASE WHEN TIPO_DE_OPERACION = 'COMPRA' THEN CANTIDAD ELSE 0 END)  over(partition by ISIN) AS CANTIDAD_COMPRAS,
		   SUM(CASE WHEN TIPO_DE_OPERACION = 'VENTA' THEN CANTIDAD ELSE 0 END)  over(partition by ISIN) AS CANTIDAD_VENTAS,
	       PRECIO_EUR
	FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
	--WHERE TIPO_DE_OPERACION = 'VENTA'
	--GROUP BY ISIN, TIPO_DE_OPERACION
	
),

CTE_SUMA_CANTIDAD_COMPRAS_VENTAS AS (
	SELECT ISIN, TIPO_DE_OPERACION, CANTIDAD, PRECIO_EUR
	FROM ( 
		SELECT ISIN, 
			   TIPO_DE_OPERACION, 
			   SUM(CASE WHEN TIPO_DE_OPERACION = 'COMPRA' THEN CANTIDAD ELSE CANTIDAD END) AS CANTIDAD,
			   SUM(PRECIO_EUR) AS PRECIO_EUR
		FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
		GROUP BY ISIN, TIPO_DE_OPERACION )
)
*/

WITH CTE_SUMA_CANTIDAD_PRECIO_EUR AS (
	SELECT ISIN, TIPO_DE_OPERACION, CANTIDAD, PRECIO_EUR
	FROM ( 
		SELECT ISIN, 
			   TIPO_DE_OPERACION, 
			   SUM(CASE WHEN TIPO_DE_OPERACION = 'COMPRA' THEN CANTIDAD ELSE CANTIDAD END) AS CANTIDAD,
			   SUM(PRECIO_EUR) AS PRECIO_EUR
		FROM "FINANZAS"."CARTERA" AS TABLA_CARTERA
		GROUP BY ISIN, TIPO_DE_OPERACION )
	
),

CTE_TABLA_PRECIOS_MEDIOS AS (
		SELECT CTE_SUMA_CANTIDAD_PRECIO_EUR.ISIN, CTE_SUMA_CANTIDAD_PRECIO_EUR.TIPO_DE_OPERACION, CTE_SUMA_CANTIDAD_PRECIO_EUR.CANTIDAD AS CANTIDAD, 
		CTE_SUMA_CANTIDAD_PRECIO_EUR.PRECIO_EUR/CANTIDAD AS PRECIO_MEDIO_EUR
		FROM CTE_SUMA_CANTIDAD_PRECIO_EUR
)


SELECT CTE_TABLA_PRECIOS_MEDIOS.ISIN, 
	TABLA_RENDIMIENTOS.TIPO_DE_ACTIVO,
	TIPO_DE_OPERACION, 
	CANTIDAD,
	CIERRE, 
	TABLA_FECHA.FECHA_ACTUAL,
	--FECHA, --Para ver las fechas diarias
	PRECIO_MEDIO_EUR,
	CIERRE-PRECIO_MEDIO_EUR AS PLUSVALIA_MINUSVALIA
FROM 
	CTE_TABLA_PRECIOS_MEDIOS 
	INNER JOIN 
	(SELECT ISIN, FECHA, CIERRE, TIPO_DE_ACTIVO FROM "FINANZAS"."RENDIMIENTOS") AS TABLA_RENDIMIENTOS

	ON TABLA_RENDIMIENTOS.ISIN = CTE_TABLA_PRECIOS_MEDIOS.ISIN

	--Hacemos cruce con este JOIN para que tome la ÚLTIMA FECHA para cada ISIN:
	INNER JOIN
		(SELECT ISIN, MAX(FECHA) AS FECHA_ACTUAL
			FROM "FINANZAS"."RENDIMIENTOS"
			GROUP BY ISIN) AS TABLA_FECHA
	ON TABLA_RENDIMIENTOS.ISIN = TABLA_FECHA.ISIN
	AND TABLA_RENDIMIENTOS.FECHA = TABLA_FECHA.FECHA_ACTUAL
;











































